---
title: "Survival Analsysis - Final Assignment"
output:
  pdf_document:
    highlight: monochrome
---

```{r}
library("survival")
library("km.ci")
library("bpcp")
library("SurvRegCensCov")
library("xtable")

rossi <- read.table(file=file.choose(),header=TRUE)
View(rossi)
attach(rossi)

```


```{r}
#Q1a

summary(rossi)

KM1<-survfit(Surv(rossi$week,rossi$arrest)~1, conf.type="log-log")
plot(survfit(Surv(rossi$week,rossi$arrest)~1),ylim=c(0.7,1), xlab="Time in weeks",ylab="Survival Probability", main="Kaplan-Meier (log-log-transformation)")

#two-sided p-value p2
fdiff<-fixtdiff(week,arrest,fin,13,doall=TRUE)
fdiff

survival_diff<-survfit(Surv(rossi$week,rossi$arrest)~rossi$fin,conf.type="none")
plot(survival_diff[1],xlab="Time in weeks",ylab="Survival",ylim=c(0.7,1), main="No Financial Aid vs Financial Aid")
lines(survival_diff[2],col="red",lty=2)

#fixed point at 3 months
points(13,0.9491,type="p")
points(13,0.958,type="p",col="red")

legend(locator(1),c("Financial Aid","No Financial Aid"),col=c(2,1),lty=1)

#Q1b
#education
survdiff(Surv(rossi$week,rossi$arrest)~rossi$fin + factor(rossi$educ))

survival_diff2<-survfit(Surv(rossi$week,rossi$arrest)~rossi$fin + factor(rossi$educ)) #p-value

summary(survival_diff2)
plot(survival_diff2[1],conf.int=F,ylim=c(0.7,1),xlab="Time in weeks",ylab="Survival Probability", main="No Financial Aid and Education")
lines(survival_diff2[2],conf.int=F,col="red")
lines(survival_diff2[3],conf.int=F,col="blue")
lines(survival_diff2[4],conf.int=F,col="green")
lines(survival_diff2[5],conf.int=F,col="orange")

legend(locator(1),c("6th grade", "7th to 9th grade","10th grade","12th grade","some college"),col=c("black","red","blue","green","orange"),lty=1)

#marital status
survdiff(Surv(rossi$week,rossi$arrest)~rossi$fin + factor(rossi$educ) + rossi$mar) #ns

survival_diff3<-survfit(Surv(rossi$week,rossi$arrest)~rossi$fin + factor(rossi$educ) + rossi$mar)

summary(survival_diff3)

#check this damn plot
plot(survival_diff3[1],xlab="Time in weeks",ylab="Survival Probability",ylim=c(0.7,1), main="No Financial Aid, Education and Marital Status")

lines(survival_diff3[2],conf.int=F,col="brown1")
lines(survival_diff3[3],conf.int=F,col="brown")
lines(survival_diff3[4],conf.int=F,col="red")
lines(survival_diff3[5],conf.int=F,col="darkred")
lines(survival_diff3[6],conf.int=F,col="blue")
lines(survival_diff3[7],conf.int=F,col="deepskyblue")
lines(survival_diff3[8],conf.int=F,col="green")
lines(survival_diff3[9],conf.int=F,col="darkgreen")
lines(survival_diff3[10],conf.int=F,col="orange")

# brown, green, darkgreen and yellow follow the same survival curve

legend(locator(1),c("ED=2,MAR=0", "ED=2,MAR=1","ED=3,MAR=0","ED=3,MAR=1","ED=4,MAR=0","ED=4,MAR=1","ED=5, MAR=0","ED=5,MAR=1","ED=6, MAR=0", "ED=6, MAR=1"),col=c("brown1","brown","red","darkred","blue","deepskyblue", "green", "darkgreen", "orange", "darkorange"),lty=1)

#work experience
survdiff(Surv(rossi$week,rossi$arrest)~rossi$fin + factor(rossi$educ) + mar +wexp ) #sig again

survival_diff3<-survfit(Surv(rossi$week,rossi$arrest)~rossi$fin + factor(rossi$educ) + mar + wexp) #is new function

summary(survival_diff3)
plot(survival_diff3,xlab="Time in weeks",ylab="Survival Probability",ylim=c(0.7,1), main=" No Financial Aid, Education, Marital Status and Experience")


```
 
#This function provides p-values for the two sample tests that the survival distributions are equal at time testtime. The tests are asymptotically normal tests and are described in Klein, et al (2007). These functions are mostly for simulations to evaluate the melded BPCP tests, see bpcp2samp and Fay et al (2015).

```{r}
#Q2a
survival_cox<-coxph(Surv(rossi$week,rossi$arrest)~rossi$fin + rossi$mar + rossi$wexp + rossi$age + rossi$prio, method="efron")    

summary(survival_cox)

survival_cox.table <- xtable(survival_cox)
print(survival_cox.table)

#Q2b
survival_cox2<-coxph(Surv(rossi$week,rossi$arrest)~rossi$fin + rossi$mar + rossi$wexp + rossi$age + rossi$prio, method="breslow")

survival_cox2<-coxph(Surv(rossi$week,rossi$arrest)~rossi$fin + rossi$mar + rossi$wexp + rossi$age + rossi$prio, method="exact")

summary(survival_cox2)

#Q2c

#check the ph assumption
survival_zph_ass<- coxph(Surv(rossi$week,rossi$arrest) ~ rossi$fin + rossi$mar + rossi$wexp + rossi$age + rossi$prio + rossi$paro + rossi$race + rossi$educ) #including all variables
survival_zph_ass

survival_zph_ass.table <- xtable(survival_zph_ass)
print(survival_zph_ass.table)

#check the cox model 1
survival_zph<-cox.zph(survival_zph_ass,transform="km",global=TRUE) 
print(survival_zph) # display the results 
plot(survival_zph, col="gold")

survival_zph.table <- xtable(survival_zph_ass)
print(survival_zph.table)

plot(survfit(fit, newdata=data.frame(age=60)),
     xscale=365.25, ) 

```



```{r}
#Q3.a

#settings
require(RcmdrPlugin.survival)

rossi2 <- unfold(rossi, time="week", event="arrest", cov=11:62, cov.names="emp")
head(rossi2, 460)

#make cox model 2 with emp
survival_cox2<-coxph(Surv(rossi2$start, rossi2$stop, rossi2$arrest.time)~rossi2$emp)
summary(survival_cox2) #signifcant

survival_zph_ass2<- cox.zph(coxph(Surv(rossi2$start, rossi2$stop, rossi2$arrest.time)~rossi2$emp)) 
survival_zph_ass2 #holds

survival_zph_ass2.table <- xtable(survival_zph_ass2)
print(survival_zph_ass2.table)

#make cox model 3, all relevant variables
survival_cox3<-coxph(Surv(start, stop, arrest.time)~emp+ fin + mar + wexp + age + prio + educ + race + paro, data=rossi2)
summary(survival_cox3)

survival_zph_ass3<- cox.zph(coxph(Surv(start, stop, arrest.time)~emp+ fin + mar + wexp + age + prio + educ + race + paro, data=rossi2)) 
survival_zph_ass3 # does not hold

survival_zph_ass3.table <- xtable(survival_zph_ass3)
print(survival_zph_ass3.table)

# ph does not hold -> include interactioneffect
survival_cox4<-coxph(Surv(start, stop, arrest.time)~emp + fin + mar + wexp + age + prio + educ + race + paro + age:stop + (prio:stop) + wexp:stop+ educ:stop + mar:stop + paro:stop + fin:stop + prio:stop, data=rossi2)

summary(survival_cox4)

survival_zph_ass4<- cox.zph(coxph(Surv(start, stop, arrest.time)~emp + fin + mar + wexp + age + prio + educ + race + paro + age:stop + wexp:stop+ educ:stop, data=rossi2)) 
survival_zph_ass4 # holds

survival_zph_ass4.table <- xtable(survival_zph_ass4)
print(survival_zph_ass4.table)

# apply a step procedure to obtain a more parsimonous model

step(survival_cox4, direction="both", trace=FALSE)

# final model
survival_cox5<-coxph(Surv(start, stop, arrest.time)~emp + fin + wexp + age + prio + educ + age:stop + wexp:stop+ educ:stop, data=rossi2)

survival_zph_ass5<- cox.zph(coxph(Surv(start, stop, arrest.time)~emp + fin + wexp + age + prio + educ + age:stop + wexp:stop+ educ:stop, data=rossi2)) 
survival_zph_ass5 # does not hold

survival_zph_ass5.table <- xtable(survival_zph_ass5)
print(survival_zph_ass5.table)

summary(survival_cox5)

survival_cox5.table <- xtable(survival_cox5)
print(survival_cox5.table)

# plot resididuals for each variable sparately, cox4
survival_cox5<-coxph(Surv(start, stop, arrest.time)~emp + fin + wexp + age + prio + educ + age:stop + wexp:stop+ educ:stop, data=rossi2)

par(mfrow=c(1,2))
resids <- residuals(survival_cox5,type="martingale")
plot(resids, ylab="Residuals",main="Plotted Residuals")

resids_pred<-predict(survival_cox5)
plot(resids_pred,resids, xlab="Prediction", ylab="Residuals", main="Residuals vs. Predicted Residuals")

par(mfrow=c(2,2))

plot(rossi2$wexp,resids,xlab="Work Experience",ylab="Residuals" )
lines(lowess(rossi2$wexp, resids))

plot(rossi2$age,resids,xlab="Age", ylab="Residuals" )
lines(lowess(rossi2$age, resids))

plot(rossi2$prio,resids, xlab="Prior Conviction", ylab="Residuals" )
lines(lowess(rossi2$prio, resids))

plot(rossi2$educ,resids, xlab="Education", ylab="Residuals" )
lines(lowess(rossi2$educ, resids))

plot(rossi2$age*rossi2$stop,resids, xlab="Age in Time", ylab="Residuals" )
lines(lowess(rossi2$age*rossi2$stop, resids))

plot(rossi2$wexp*rossi2$stop,resids, xlab="Work experience in Time", ylab="Residuals" )
lines(lowess(rossi2$wexp*rossi2$stop, resids))

plot(rossi2$educ*rossi2$stop,resids, xlab="Education in Time", ylab="Residuals" )
lines(lowess(rossi2$educ*rossi2$stop, resids))

plot(rossi2$emp ,resids, xlab="Employment", ylab="Residuals" )
lines(lowess(rossi2$emp, resids))

```

```{r}
#Q4.a

#fit Weibull
Weibull<-survreg(Surv(week,arrest)~fin + wexp, data=rossi, dist="weibull")
summary(Weibull) # values are not in terms of survival

#withdraw paramters
Weibull.p<-Weibull$coef
Weibull.p
Weibull.logscale<-log(Weibull$scale)
Weibull.var<-Weibull$var

#Weibull-estimates
ps_aft<-c(exp(-Weibull.p[1]*exp(-Weibull.logscale)),exp(-Weibull.logscale),-Weibull.p[2]*exp(-Weibull.logscale), -Weibull.p[3]*exp(-Weibull.logscale))

ps_aft

ps_aft.table <- xtable(ps_aft)
print(ps_aft.table)

#check if estimates are correct (yes, they are)
reg2<-WeibullReg(Surv(week,arrest)~fin + wexp, data=rossi)
reg2$coef

#Q4b Graphics on all 3 methods for all 4 groups

#KM
g1<-subset(rossi,fin==0 & wexp==0)
g2<-subset(rossi,fin==1 & wexp==0)
g3<-subset(rossi,fin==0 & wexp==1)
g4<-subset(rossi,fin==1 & wexp==1)

KM_1<-survfit(Surv(g1$week,g1$arrest)~g1$fin + g1$wexp, conf.type="log-log")
plot(survfit(Surv(g1$week,g1$arrest)~g1$fin + g1$wexp), xlab="Time in weeks",ylab="Survival Probability", main="Kaplan-Meier G1 (log-log-transformation)")

KM_2<-survfit(Surv(g2$week,g2$arrest)~g2$fin + g2$wexp, conf.type="log-log")
plot(survfit(Surv(g2$week,g2$arrest)~g2$fin + g2$wexp), xlab="Time in weeks",ylab="Survival Probability", main="Kaplan-Meier G2 (log-log-transformation)")

KM_3<-survfit(Surv(g3$week,g3$arrest)~g3$fin + g3$wexp, conf.type="log-log")
plot(survfit(Surv(g3$week,g3$arrest)~g3$fin + g3$wexp), xlab="Time in weeks",ylab="Survival Probability", main="Kaplan-Meier G3 (log-log-transformation)")

KM_4<-survfit(Surv(g4$week,g4$arrest)~g4$fin + g4$wexp, conf.type="log-log")
plot(survfit(Surv(g4$week,g4$arrest)~g4$fin + g4$wexp), xlab="Time in weeks",ylab="Survival Probability", main="Kaplan-Meier G4 (log-log-transformation)")
#plot all KM
plot(KM_1, conf.int=F,xlab="Time in weeks",ylab="Survival Probability", main="Comparison of all 4 Groups" )
lines(KM_2,conf.int=F,col="red")
lines(KM_3,conf.int=F,col="blue")
lines(KM_4,conf.int=F,col="green")

legend(locator(1),c("FIN=0 & WEXP=0","FIN=0 & WEXP=1","FIN=1 & WEXP=0","FIN=1 & WEXP=1"),col=c("black","red","blue","green"),lty=1)

#Cox
cox.frame<- expand.grid(fin=c(0,1),wexp=c(0,1))
cox.x <- coxph(Surv(week, arrest) ~ fin + wexp, data=rossi)

#Weibull
x<-seq(0,12000,1)
KM with weibull baseline in proportional hazard model
all<-survfit(Surv(week,arrest)~fin + wexp ,conf.type="none",data=rossi)
summary(all)

plot(all[1],xlab="Time",lty=1,ylab="Survival",col="black",ylim=c(0.7,1),main="KM Estimates, Weibull and Cox's Survival Functions")
lines(all[1],lty=3,col="black")
lines(all[2],lty=2,col="red")
lines(all[3],lty=1,col="blue")
lines(all[4],lty=2,col="green")

lines(x,pweibull(x,shape=1/Weibull$scale,scale=exp(Weibull.p[1]),lower.tail=F),lty=1,col="black")
lines(x,pweibull(x,shape=1/Weibull$scale,scale=exp(Weibull.p[1]+Weibull.p[3]),lower.tail=F),lty=2,col="darkred")
lines(x,pweibull(x,shape=1/Weibull$scale,scale=exp(Weibull.p[1]+Weibull.p[2]),lower.tail=F),
 lty=2,col="darkblue")
lines(x,pweibull(x,shape=1/Weibull$scale,scale=exp(Weibull.p[1]+Weibull.p[2]+Weibull.p[3]),lower.tail=F), lty=2,col="darkgreen")


lines(survfit(cox.x, newdata=cox.frame[1,], col="azure4", conf.int=F))
lines(survfit(cox.x, newdata=cox.frame[2,], col="coral", conf.int=F))
lines(survfit(cox.x, newdata=cox.frame[3,], col="cyan", conf.int=F))
lines(survfit(cox.x, newdata=cox.frame[4,], col="darkolivegreen1", conf.int=F))

legend("bottomleft",legend=c("F0,W0","F0,W1","F1,W0","F1,W1"),col=c("black","red","blue","green"),lty=1)

 ```
